### VIX (CBOE Volatility Index) is a popular measure of the stock market's expectation of volatility implied by S&P 500 index options. This data will be used to determine if volatility in the markets impacts price of bitcoin.

In [1]:
#Import required packages 
import numpy as np
import pandas as pd
import pandas_profiling
from datetime import datetime
import pickle

In [111]:
vix_volatility_hourly_history_df = pd.read_csv('./data/vix_volatility_hourly_history.csv')

In [112]:
vix_volatility_hourly_history_df['date'] = vix_volatility_hourly_history_df['Local time'].astype(str).str[5:]

In [113]:
vix_volatility_hourly_history_df['date_1'] = vix_volatility_hourly_history_df['Local time'].astype(str).str[0:2]

In [114]:
vix_volatility_hourly_history_df['date_2'] = vix_volatility_hourly_history_df['Local time'].astype(str).str[3:5]

In [117]:
vix_volatility_hourly_history_df['local_time'] = vix_volatility_hourly_history_df['date_2'] + '.' + vix_volatility_hourly_history_df['date_1'] + vix_volatility_hourly_history_df['date']
vix_volatility_hourly_history_df.drop(['date', 'date_1', 'date_2'], axis = 1, inplace = True)

In [118]:
vix_volatility_hourly_history_df.head(2)

,Local time,Open,High,Low,Close,Volume,local_time
0,26.01.2017 00:00:00.000 GMT-0800,19.14,19.14,19.14,19.14,0.0,01.26.2017 00:00:00.000 GMT-0800
1,26.01.2017 01:00:00.000 GMT-0800,19.14,19.14,19.14,19.14,0.0,01.26.2017 01:00:00.000 GMT-0800

In [119]:
vix_volatility_hourly_history_df['local_time'] = pd.to_datetime(vix_volatility_hourly_history_df['local_time'], utc = True)

In [78]:
# #Strip Timezone Info
# vix_volatility_hourly_history_df['Local_time_2'] = vix_volatility_hourly_history_df['Local time'].astype(str).str[:-9]

# #Convert all string dates to datetime
# vix_volatility_hourly_history_df['local_time'] = pd.to_datetime(vix_volatility_hourly_history_df['Local_time_2'])
# vix_volatility_hourly_history_df.drop(['Local_time_2'], axis = 1, inplace = True)

In [68]:
pandas_profiling.ProfileReport(vix_volatility_hourly_history_df)

In [69]:
vix_volatility_hourly_history_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20735 entries, 0 to 20734
Data columns (total 6 columns):
Local time    20735 non-null datetime64[ns]
Open          20735 non-null float64
High          20735 non-null float64
Low           20735 non-null float64
Close         20735 non-null float64
Volume        20735 non-null float64
dtypes: datetime64[ns](1), float64(5)
memory usage: 972.0 KB

In [122]:
vix_volatility_hourly_history_df[vix_volatility_hourly_history_df.local_time == '2018-11-03 17:00:00+00:00']

,Local time,Open,High,Low,Close,Volume,local_time
15527,04.11.2018 00:00:00.000 GMT-0700,36.627,36.627,36.627,36.627,0.0,2018-11-03 17:00:00+00:00
15529,04.11.2018 01:00:00.000 GMT-0800,36.627,36.627,36.627,36.627,0.0,2018-11-03 17:00:00+00:00

In [123]:
vix_volatility_hourly_history_df[15526:15531]

,Local time,Open,High,Low,Close,Volume,local_time
15526,03.11.2018 23:00:00.000 GMT-0700,36.627,36.627,36.627,36.627,0.0,2018-11-03 16:00:00+00:00
15527,04.11.2018 00:00:00.000 GMT-0700,36.627,36.627,36.627,36.627,0.0,2018-11-03 17:00:00+00:00
15528,04.11.2018 01:00:00.000 GMT-0700,36.627,36.627,36.627,36.627,0.0,2018-11-03 18:00:00+00:00
15529,04.11.2018 01:00:00.000 GMT-0800,36.627,36.627,36.627,36.627,0.0,2018-11-03 17:00:00+00:00
15530,04.11.2018 02:00:00.000 GMT-0800,36.627,36.627,36.627,36.627,0.0,2018-11-03 18:00:00+00:00

In [126]:
vix_volatility_hourly_history_df.drop(15529, inplace = True)

In [127]:
vix_volatility_hourly_history_df[15526:15531]

,Local time,Open,High,Low,Close,Volume,local_time
15526,03.11.2018 23:00:00.000 GMT-0700,36.627,36.627,36.627,36.627,0.0,2018-11-03 16:00:00+00:00
15527,04.11.2018 00:00:00.000 GMT-0700,36.627,36.627,36.627,36.627,0.0,2018-11-03 17:00:00+00:00
15528,04.11.2018 01:00:00.000 GMT-0700,36.627,36.627,36.627,36.627,0.0,2018-11-03 18:00:00+00:00
15530,04.11.2018 02:00:00.000 GMT-0800,36.627,36.627,36.627,36.627,0.0,2018-11-03 18:00:00+00:00
15531,04.11.2018 03:00:00.000 GMT-0800,36.627,36.627,36.627,36.627,0.0,2018-11-03 19:00:00+00:00

In [128]:
vix_volatility_hourly_history_df.drop(15530, inplace = True)

In [130]:
vix_volatility_hourly_history_df[vix_volatility_hourly_history_df.local_time == '2017-11-04 18:00:00+00:00']

,Local time,Open,High,Low,Close,Volume,local_time
6792,05.11.2017 01:00:00.000 GMT-0700,33.647,33.647,33.647,33.647,0.0,2017-11-04 18:00:00+00:00
6794,05.11.2017 02:00:00.000 GMT-0800,33.647,33.647,33.647,33.647,0.0,2017-11-04 18:00:00+00:00

In [131]:
vix_volatility_hourly_history_df[6790:6796]

,Local time,Open,High,Low,Close,Volume,local_time
6790,04.11.2017 23:00:00.000 GMT-0700,33.647,33.647,33.647,33.647,0.0,2017-11-04 16:00:00+00:00
6791,05.11.2017 00:00:00.000 GMT-0700,33.647,33.647,33.647,33.647,0.0,2017-11-04 17:00:00+00:00
6792,05.11.2017 01:00:00.000 GMT-0700,33.647,33.647,33.647,33.647,0.0,2017-11-04 18:00:00+00:00
6793,05.11.2017 01:00:00.000 GMT-0800,33.647,33.647,33.647,33.647,0.0,2017-11-04 17:00:00+00:00
6794,05.11.2017 02:00:00.000 GMT-0800,33.647,33.647,33.647,33.647,0.0,2017-11-04 18:00:00+00:00
6795,05.11.2017 03:00:00.000 GMT-0800,33.647,33.647,33.647,33.647,0.0,2017-11-04 19:00:00+00:00

In [132]:
vix_volatility_hourly_history_df.drop([6793, 6794, ], inplace = True)

In [133]:
vix_volatility_hourly_history_df[6790:6796]

,Local time,Open,High,Low,Close,Volume,local_time
6790,04.11.2017 23:00:00.000 GMT-0700,33.647,33.647,33.647,33.647,0.0,2017-11-04 16:00:00+00:00
6791,05.11.2017 00:00:00.000 GMT-0700,33.647,33.647,33.647,33.647,0.0,2017-11-04 17:00:00+00:00
6792,05.11.2017 01:00:00.000 GMT-0700,33.647,33.647,33.647,33.647,0.0,2017-11-04 18:00:00+00:00
6795,05.11.2017 03:00:00.000 GMT-0800,33.647,33.647,33.647,33.647,0.0,2017-11-04 19:00:00+00:00
6796,05.11.2017 04:00:00.000 GMT-0800,33.647,33.647,33.647,33.647,0.0,2017-11-04 20:00:00+00:00
6797,05.11.2017 05:00:00.000 GMT-0800,33.647,33.647,33.647,33.647,0.0,2017-11-04 21:00:00+00:00

In [134]:
vix_volatility_hourly_history_df['local_time'].value_counts()

2017-09-18 20:00:00+00:00    1
2019-04-27 08:00:00+00:00    1
2018-07-23 14:00:00+00:00    1
2019-05-11 23:00:00+00:00    1
2018-07-11 08:00:00+00:00    1
2017-04-23 17:00:00+00:00    1
2018-12-18 13:00:00+00:00    1
2018-12-26 18:00:00+00:00    1
2017-07-28 00:00:00+00:00    1
2018-12-08 03:00:00+00:00    1
2017-11-09 16:00:00+00:00    1
2018-08-07 23:00:00+00:00    1
2017-04-05 19:00:00+00:00    1
2018-12-22 07:00:00+00:00    1
2018-11-07 04:00:00+00:00    1
2017-07-10 02:00:00+00:00    1
2017-10-02 22:00:00+00:00    1
2017-10-11 04:00:00+00:00    1
2018-11-01 05:00:00+00:00    1
2017-08-14 22:00:00+00:00    1
2017-10-08 03:00:00+00:00    1
2017-12-09 10:00:00+00:00    1
2018-11-11 12:00:00+00:00    1
2018-04-16 06:00:00+00:00    1
2018-04-08 13:00:00+00:00    1
2019-03-01 08:00:00+00:00    1
2017-11-23 14:00:00+00:00    1
2017-05-29 13:00:00+00:00    1
2018-02-16 22:00:00+00:00    1
2018-01-12 10:00:00+00:00    1
                            ..
2017-02-12 03:00:00+00:00    1
2018-07-19 13:00:00+00:00    1
2018-04-11 10:00:00+00:00    1
2018-04-07 10:00:00+00:00    1
2018-08-12 00:00:00+00:00    1
2018-01-09 13:00:00+00:00    1
2017-02-03 04:00:00+00:00    1
2017-08-30 16:00:00+00:00    1
2018-03-14 17:00:00+00:00    1
2018-03-19 04:00:00+00:00    1
2018-07-02 07:00:00+00:00    1
2018-12-31 10:00:00+00:00    1
2018-06-09 11:00:00+00:00    1
2018-10-30 16:00:00+00:00    1
2017-04-06 21:00:00+00:00    1
2018-12-24 22:00:00+00:00    1
2018-09-19 17:00:00+00:00    1
2017-12-20 16:00:00+00:00    1
2017-03-28 22:00:00+00:00    1
2018-12-14 10:00:00+00:00    1
2018-12-16 10:00:00+00:00    1
2018-05-02 00:00:00+00:00    1
2017-03-19 23:00:00+00:00    1
2017-09-30 13:00:00+00:00    1
2019-02-19 12:00:00+00:00    1
2018-07-09 22:00:00+00:00    1
2017-11-16 22:00:00+00:00    1
2018-01-04 21:00:00+00:00    1
2017-03-11 00:00:00+00:00    1
2019-01-15 12:00:00+00:00    1
Name: local_time, Length: 20731, dtype: int64

In [121]:
vix_volatility_hourly_history_df.head()

,Local time,Open,High,Low,Close,Volume,local_time
0,26.01.2017 00:00:00.000 GMT-0800,19.14,19.14,19.14,19.14,0.0,2017-01-25 16:00:00+00:00
1,26.01.2017 01:00:00.000 GMT-0800,19.14,19.14,19.14,19.14,0.0,2017-01-25 17:00:00+00:00
2,26.01.2017 02:00:00.000 GMT-0800,19.14,19.14,19.14,19.14,0.0,2017-01-25 18:00:00+00:00
3,26.01.2017 03:00:00.000 GMT-0800,19.14,19.14,19.14,19.14,0.0,2017-01-25 19:00:00+00:00
4,26.01.2017 04:00:00.000 GMT-0800,19.14,19.14,19.14,19.14,0.0,2017-01-25 20:00:00+00:00

In [26]:
vix_volatility_hourly_history_df.to_pickle('./data/vix_volatility_hourly_history_df.pickle')